### ISSUE TITLE
Volumes on Azure Stack Hub do not have correct topology

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/azuredisk-csi-driver#1013]
**What happened**:
Running v1.5.1 on Azure Stack Hub, I noticed that PVs have a wrong affinity and nodes have wrong labels.

 PV:
```
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.disk.csi.azure.com/zone
            operator: In
            values:
            - ""
```

Node:
```
      topology.disk.csi.azure.com/zone: ""
      topology.kubernetes.io/region: ppe3
      topology.kubernetes.io/zone: "1"
```

So, the external cloud controller knows correct location (ppe3/1), but the CSI driver does not.

**What you expected to happen**:
Both PVs and Nodes would have some topology, either `topology.disk.csi.azure.com/zone: 1` or `ppe3-1`

**How to reproduce it**:
Run the CSI driver in AzureStackHub with cloud config with `"useInstanceMetadata":false`.

**Anything else we need to know?**:
Looking at the code in [NodeGetInfo](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/4c052cc47c2d67d8bbffbb31f13bbf33ca4d0630/pkg/azuredisk/nodeserver.go#L321), I can see

* `zone`, as returned by `d.cloud.GetZone(ctx)`,  is `{FailureDomain:1 Region:ppe3}`
* `d.cloud.Location` is `ppe3`
* `isAvailabilityZone` checks that `FailureDomain` has prefix `ppe3`, which it does not and therefore the driver reports `{"accessible_topology":{"segments":{"topology.disk.csi.azure.com/zone":""}}`

**Environment**:
- CSI Driver version: 1.5.1
- Kubernetes version (use `kubectl version`): v1.22.0-rc.0
- OS (e.g. from /etc/os-release): RHEL 8.4
- Kernel (e.g. `uname -a`):  4.18.0-305.12.1.el8_4.x86_64
- Install tools: OpenShift
