### ISSUE TITLE
Volumesnapshot's snapshotHandle is not working as intended.

### ISSUE THREAD

**Issue by kutysam** [kubernetes-sigs/azuredisk-csi-driver#1031]
**What happened**: Azure CSI isn't creating a volume from a snapshot but instead creates a fresh disk

**What you expected to happen**: Azure CSI is supposed to create a volume from the specified snapshot

**How to reproduce it**: Use the yamls
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvca
  namespace: default
spec:
  storageClassName: default
  dataSource:
    name: vsa
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: vsa
spec:
  volumeSnapshotClassName: csi-azuredisk-vsc
  source:
    volumeSnapshotContentName: vsca
---
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  finalizers:
    - snapshot.storage.kubernetes.io/volumesnapshotcontent-bound-protection
  name: vsca
spec:
  deletionPolicy: Retain
  driver: disk.csi.azure.com
  source:
    snapshotHandle: /subscriptions/SUBSCRIPTION_ID/resourceGroups/MC_FILLITIN/providers/Microsoft.Compute/snapshots/YOURSNAPSHOT
  volumeSnapshotClassName: csi-azuredisk-vsc
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: vsa
    namespace: default
```

**Anything else we need to know?**: I have purposely changed my YOURSNAPSHOT to a snapshot that doesn't exist and it throws an error and when i put the correct snapshot in, it does not throw an error, So i'm pretty sure the snapshothandle is correctly done. I've the same setup on AWS and it is working well.

**Environment**:
- CSI Driver version: 1.7.0
- Kubernetes version (use `kubectl version`):  1.20.9
- OS (e.g. from /etc/os-release): Azure aks
- Kernel (e.g. `uname -a`): Azure aks
- Install tools: Fresh aks with csi installed
- Others: NA

**Comment by andyzhangx** [comment]
hi @kutysam can you provide disk controller logs, follow guide here: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/csi-debug.md#case1-disk-createdeleteattachdetachsnapshotrestore-failed
it should have `/CreateSnapshot` logs

**Comment by andyzhangx** [comment]
you should change `snapshotHandle` to `volumeHandle` in `VolumeSnapshotContent`, other fields are correct.

**Comment by kutysam** [comment]
Hi @andyzhangx 
Unfortunately, I only can try to get the logs in the weekend.
However, to your last comment, I am using a snapshot and not a volume. Snapshot handle is accepted in the crd and snapshothandle is working well for aws when i tested with the same approach.

> you should change `snapshotHandle` to `volumeHandle` in `VolumeSnapshotContent`, other fields are correct. , e.g.
> 
> ```yaml
> apiVersion: v1
> items:
> - apiVersion: snapshot.storage.k8s.io/v1
>   kind: VolumeSnapshotContent
>   metadata:
>     ...
>   spec:
>     deletionPolicy: Delete
>     driver: disk.csi.azure.com
>     source:
>       volumeHandle: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/disks/pvc-9ebc03d4-95a3-4104-9fb9-265ed36601f9
>     volumeSnapshotClassName: csi-azuredisk-vsc
> ```

**Comment by andyzhangx** [comment]
hi @kutysam, I tried with `snapshotHandle`, it works well, the restored pvc has snapshot data.
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotContent
metadata:
  name: vsca
spec:
  deletionPolicy: Retain
  driver: disk.csi.azure.com
  source:
    snapshotHandle: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/snapshots/snapshot-18a51b04-1a3e-4e42-8461-6ce6e7fd643e
```

I used this example: https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/snapshot, one thing need to mention that after testing pod `nginx-pod-azuredisk` is created, need to wait a moment for that pod writing data successfully.

```console
# k exec -it nginx-restored2 -- ls /mnt/azuredisk/ -lt
total 116
-rw-r--r--    1 root     root        100543 Sep 27 12:39 outfile
drwx------    2 root     root         16384 Sep 27 11:41 lost+found
```
