### ISSUE TITLE
Values of tags attached to actual Azure snapshot do not match VolumeSnapshotClass definition

### ISSUE THREAD

**Issue by log2** [kubernetes-sigs/azuredisk-csi-driver#1139]
**What happened**:

Added a VolumeSnapshotClass with two or more tags, such as:

```
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: disk.csi.azure.com
kind: VolumeSnapshotClass
metadata:
  name: my-vsc
parameters:
  incremental: "true"
  tags: a=b,c=d,e=f
```

Then created a VolumeSnapshot using it, such as:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: vs
spec:
  source:
    persistentVolumeClaimName: my-pvc
  volumeSnapshotClassName: my-vsc
```

The snapshot that gets created in Azure has the following tags:

- `a`: `f`
- `c`: `f`
- `e`: `f`

**What you expected to happen**:

I expected that Azure snapshot had the following tags, as specified in `parameters.tags` field:

- `a`: `b`
- `c`: `d`
- `e`: `f`

**How to reproduce it**:

Just add two or more tags with different values; there are no issues when just one tag is present.

**Anything else we need to know?**:

This issue could be related to the following line: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/3d730ced91d16ae83ac15da287f6fba3fc1fcb28/pkg/azuredisk/controllerserver_v2.go#L805

I'm not sure, but perhaps this bug could be fixed by changing the previous line from `tags[k] = &v` to `tags[k] = v` .

On the other hand, the tag parser seems fine: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/3d730ced91d16ae83ac15da287f6fba3fc1fcb28/pkg/util/util.go#L83

**Environment**:
- CSI Driver version: `v1.8.0`
- Kubernetes version (use `kubectl version`): `v1.21.7`
