### ISSUE TITLE
Live resizing doesn't work, the AKS node doesn't see the new disk size without manual rescan

### ISSUE THREAD

**Issue by bandesz** [kubernetes-sigs/azuredisk-csi-driver#1157]
**What happened**:

Tested the live resizing feature on a new vanilla AKS 1.21 cluster in eastus2euap.

Subscription is signed up for the LiveResize feature:
```
az feature show --namespace Microsoft.Compute --name LiveResize

{
  "id": "/subscriptions/xxx/providers/Microsoft.Features/providers/Microsoft.Compute/features/LiveResize",
  "name": "Microsoft.Compute/LiveResize",
  "properties": {
    "state": "Registered"
  },
  "type": "Microsoft.Features/providers/features"
}
```

I had to trigger a manual device rescan for the live resizing to finish.

**What you expected to happen**:

Live resizing to work without manual steps on the VM.

**How to reproduce it**:

1. Create a statefulset for testing, wait for the nginx pod to be running

```
kubectl apply -f workload.yaml
```

2. Request a bigger volume size in pvc:
```
kubectl -n nginx patch pvc nginx-logs-nginx-0 -p '{"spec":{"resources":{"requests":{"storage":"2Gi"}}}}'
```

3. Wait for the persistent volume to be resized
```
kubectl get pv --watch
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                      STORAGECLASS   REASON   AGE
pvc-9e968ce5-b47c-47d4-bac9-210d09246103   1Gi        RWO            Delete           Bound    nginx/nginx-logs-nginx-0   nginx                   117s
pvc-9e968ce5-b47c-47d4-bac9-210d09246103   2Gi        RWO            Delete           Bound    nginx/nginx-logs-nginx-0   nginx                   4m38s
```

4. Online resizing doesn't happen and this event is logged:

```
0s          Warning   VolumeResizeFailed         pod/nginx-0                                NodeExpandVolume.NodeExpandVolume failed for volume "pvc-9e968ce5-b47c-47d4-bac9-210d09246103" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = resize requested for 2, but after resizing volume size was 1
```

5. PVC status
```
k -n nginx get pvc nginx-logs-nginx-0 -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
    volume.kubernetes.io/selected-node: aks-agentpool-25706065-vmss000002
  creationTimestamp: "2022-01-27T12:51:31Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: nginx
  name: nginx-logs-nginx-0
  namespace: nginx
  resourceVersion: "14003"
  uid: 9e968ce5-b47c-47d4-bac9-210d09246103
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nginx
  volumeMode: Filesystem
  volumeName: pvc-9e968ce5-b47c-47d4-bac9-210d09246103
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-27T12:56:12Z"
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
    status: "True"
    type: FileSystemResizePending
  phase: Bound
```

6. SSHd onto the node and ran the same command as the csi driver node agent:
```
sudo blockdev --getsize64 /dev/sdc
1073741824

sudo resize2fs /dev/sdc
resize2fs 1.44.1 (24-Mar-2018)
The filesystem is already 262144 (4k) blocks long.  Nothing to do!
```

The problem is that the system still sees the old 1Gi size.

7. Trigger a rescan for the sdc device:

```
$ echo 1>/sys/class/block/sdc/device/rescan
$ blockdev --getsize64 /dev/sdc
2147483648
```

The node agent was able to finish resizing successfully shortly after this, `df -h` shows the new size in the pod too:

```
/dev/sdc        2.0G  3.0M  2.0G   1% /var/log/nginx
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: v1.10.0
- Kubernetes version (use `kubectl version`): v1.21.7
- OS (e.g. from /etc/os-release): `Ubuntu 20.04.3 LTS (Focal Fossa)`
- Kernel (e.g. `uname -a`): `Linux aks-agentpool-25706065-vmss000002 5.4.0-1067-azure #70~18.04.1-Ubuntu SMP Thu Jan 13 19:46:01 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

## Appendix

workload.yaml
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nginx
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
parameters:
  skuname: StandardSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx
  labels:
    app: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.17.6
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/log/nginx"
              name: nginx-logs
              readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: nginx-logs
      spec:
        storageClassName: nginx
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
```
