### ISSUE TITLE
Mount a shared Azure disk in Azure Kubernetes to multiple windows PODs

### ISSUE THREAD

**Issue by surajpunugade** [kubernetes-sigs/azuredisk-csi-driver#1182]
**What happened**:
I want to attach a shared disk to multiple windows containers on AKS. 
Followed the similar steps from [wiki](https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/sharedisk) to create PV, PVC, and deployment.
Its failing with below error

>MapVolume.MapPodDevice failed for volume "pvc-6e07bdca-2126-4a5b-806a-026016c3798d" : rpc error: code = Internal desc = Could not mount "2" at "\var\lib\kubelet\plugins\kubernetes.io\csi\volumeDevices\publish\pvc-6e07bdca-2126-4a5b-806a-026016c3798d\4e44da87-ea33-4d85-a7db-076db0883bcf": rpc error: code = Unknown desc = not an absolute Windows path: 2

<img width="1074" alt="2022-02-16 18_14_12-Clipboard" src="https://user-images.githubusercontent.com/7521482/154331389-ff328b74-147c-426a-9dee-17552831d33b.png">

**What you expected to happen**:
Expected to attach a shared disk between multiple window pods on AKS.

**How to reproduce it**:
Used below scripts to dynamically provision Shared Azure Disk

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-custom
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS  
  maxShares: "2"
  cachingMode: None
reclaimPolicy: Delete
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-azuredisk-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi  
  volumeMode: Block
  storageClassName: managed-csi-custom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-shared-disk
  name: deployment-azuredisk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-shared-disk
  template:
    metadata:
      labels:
        app: test-shared-disk
      name: deployment-azuredisk
    spec:
      nodeSelector:
        role: windowsgeneral
      containers:
        - name: deployment-azuredisk
          image: mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019
          volumeDevices:
            - name: azuredisk
              devicePath: "D:\test"
      volumes:
        - name: azuredisk
          persistentVolumeClaim:
            claimName: pvc-azuredisk-dynamic
```

**Environment**:
- CSI Driver version: 1.9.0
- Kubernetes version: 1.21.2
- OS (e.g. from /etc/os-release): AKSWindows-2019-17763.2300.211110
