### ISSUE TITLE
Parameter cachingMode either broken or confusing

### ISSUE THREAD

**Issue by mattsheerin** [kubernetes-sigs/azuredisk-csi-driver#1226]
**What happened**: I used the disk.csi.azure.com driver for a persistentVolume with `cachingMode: None` in an attempt to work around https://github.com/kubernetes/kubernetes/issues/43916, but it seemed to have no effect on disk caching behaviour and the bug was still easily reproducible. Either the config didn't work, or it's somehow referring to some other kind of disk caching that's unhelpful to me - so either a code bug or the docs aren't clear enough.

I'll also happily accept good suggestions for other ways of disabling disk cache for my container/volume.

**What you expected to happen**: Disk cache to not be used for data written to this volume, thereby avoiding the k8s bug.

**How to reproduce it**: Run an IO-heavy workload in a container writing to a persistentVolume using disk.csi.azure.com and `cachingMode: None`. Observe memory usage increase due to the kernel's disk cache filling up.

**Anything else we need to know?**: No.

**Environment**:
- CSI Driver version: Don't know, not obviously visible to me when inspecting the storageclasses.storage.k8s.io or pv objects.
- Kubernetes version (use `kubectl version`): v1.21.9
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1070-azure
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could you check whether `Host caching` is set as `None` in azure portal after you create a pod with disk mount?
If it's already `None`, then it could be vm setting issue instead of csi driver issue. Thanks.

![image](https://user-images.githubusercontent.com/4178417/158927537-4f19e056-0bd8-4d9d-9a88-06a606c5b34c.png)

**Comment by mattsheerin** [comment]
I've dug around in the portal looking at my AKS cluster and the disk, but I can't seem to find a table that looks like that, or indeed any that list the "Host caching" for the volume. I checked the pv with kubectl instead, where I've redacted a field to avoid posting the subscription ID:
`kubectl get pv pvc-4c17edba-95e7-483f-a12a-65c9ddd5e8e8 -o yaml | yq .spec.csi`

```yaml
{
  "driver": "disk.csi.azure.com",
  "volumeAttributes": {
    "cachingMode": "None",
    "csi.storage.k8s.io/pv/name": "pvc-4c17edba-95e7-483f-a12a-65c9ddd5e8e8",
    "csi.storage.k8s.io/pvc/name": "data-sas-sas-mjs-ado-93464-data-0",
    "csi.storage.k8s.io/pvc/namespace": "sas",
    "requestedsizegib": "1024",
    "skuName": "StandardSSD_LRS",
    "storage.kubernetes.io/csiProvisionerIdentity": "1647511859445-8081-disk.csi.azure.com"
  },
  "volumeHandle": "redacted"
}
```
