### ISSUE TITLE
Requesting `iopsPerGB` or `allowAutoIOPSPerGBIncrease ` for ultradisk parameter. 

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes-sigs/azuredisk-csi-driver#1442]
**Is your feature request related to a problem?/Why is this needed**

if your storage class is like below (with ultradisk as the sku name), the default provisioned IOPS for such disk is 500
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: ultra-disk
parameters:
  cachingMode: None
  skuname: UltraSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

```

when you provision a PVC with disksize greater than 500GB it results in the following error.

```json
"statusMessage": "{\"error\":{\"code\":\"BadRequest\",\"message\":\"The value 500 of parameter disk.diskIOPSReadWrite is not valid. The supported range for a UltraSSD_LRS disk of size 512 GB is between 512 and 153600.\"}}",
```

Our pods are in pending and this is affecting our customers from provisioning Ultradisk over 500GB of disk capacity. 

**Describe the solution you'd like in detail**

We need something like `iopsPerGB ` as explained [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/parameters.md) in aws-ebs's driver or a flag like this `allowAutoIOPSPerGBIncrease` that sets a meaningful default IOPS so that Volume mount wont fail. 

can this flag also be mutable to existing StorageClass so that we dont have to create a new storage to support this feature? 

**Describe alternatives you've considered**

**Additional context**

Note: Support request ID	2207310050000344 and affecting our production system right now.

**Comment by dhilipkumars** [comment]
cc: @andyzhangx

**Comment by andyzhangx** [comment]
thanks, this issue would be fixed in v1.22.0 csi driver version.

**Comment by dhilipkumars** [comment]
Thanks @andyzhangx for such a quick response, any schedule on when will we get `v1.22.0` out ?

**Comment by andyzhangx** [comment]
hi @dhilipkumars , the open source v1.22.0 release of this csi driver would be end of this week, while aks rollout would be early next month, before that, I think you could set the `DiskIOPSReadWrite: "512"` or larger in storage class as a workaround

**Comment by dhilipkumars** [comment]
@andyzhangx thanks for the update, we tested the fix today and found another edge case here for 65TB disk creation , but this time its for `throughput` value instead of IOPS.

```
  "error": {
    "code": "BadRequest",
    "message": "The value 255 of parameter disk.diskMBpsReadWrite is not valid. The supported range for a UltraSSD_LRS disk of size 65535 GB is between 256 and 4000."
  }
}
```

**Comment by andyzhangx** [comment]
> @andyzhangx thanks for the update, we tested the fix today and found another edge case here for 65TB disk creation , but this time its for `throughput` value instead of IOPS.
> 
> ```
>   "error": {
>     "code": "BadRequest",
>     "message": "The value 255 of parameter disk.diskMBpsReadWrite is not valid. The supported range for a UltraSSD_LRS disk of size 65535 GB is between 256 and 4000."
>   }
> }
> ```

@dhilipkumars what csi driver version are you trying? v1.22.0 is just rolling out now. The default value of `disk.diskMBpsReadWrite` for 65TB disk creation is `625` on v1.22.0 version.

**Comment by dhilipkumars** [comment]
@andyzhangx here is my csi dirver v1.22.0
```
$k -n kube-system get ds csi-azuredisk-node -o yaml | grep image
        image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.6.0
        imagePullPolicy: IfNotPresent
        image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.5.0
        imagePullPolicy: IfNotPresent
        image: mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.22.0
        imagePullPolicy: IfNotPresent
```

**Comment by dhilipkumars** [comment]
Here is the PVC spec, the storage class has no IOPS or throughput value. 
```
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 65535Gi
  storageClassName: edb-azure-ultra-v1

```

**Comment by dhilipkumars** [comment]
here it is. 
```
parameters:
  cachingMode: None
  fsType: ext4
  skuname: UltraSSD_LRS
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
