### ISSUE TITLE
ultradisk pvc leaves doesnt cleanup condition

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes-sigs/azuredisk-csi-driver#1461]
**What happened**:
```
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-08-10T23:12:10Z"
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
    status: "True"
    type: FileSystemResizePending
  phase: Bound

```
**What you expected to happen**:
When the driver has completed a  resized,  and there is no pod bound to this PVC yet then it still does not remove the above condition.  Our controller checking these conditions [here](https://github.com/cloudnative-pg/cloudnative-pg/blob/main/pkg/specs/pvcs.go#L192) continues to wait without spinning up the pod. 

If the resize is completed the above condition should be removed by the controller.  

**How to reproduce it**:

- Create a azure ultradisk PVC 
- Create a deployment claiming the PVC
- Resize the PVC size
- scale the deployment to '0' replicas
- wait for the csi-driver to complete resize
- check the pvc's condition. 

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.20.0
- Kubernetes version (use `kubectl version`):   AKS: v1.22.11
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
