### ISSUE TITLE
[Helm chart] add support for VolumeSnapshotClass

### ISSUE THREAD

**Issue by janaurka** [kubernetes-sigs/azuredisk-csi-driver#1710]
**Is your feature request related to a problem?/Why is this needed**
The helm-chart (GA and 2.0 beta) are currently lacking the support of adding `VolumeSnapshotClass` next to the CSI installation.

It is covered in the [documentation](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml) and would ease up things, having this directly in the chart. I have also created a feature request for the [`velero` chart](https://github.com/vmware-tanzu/helm-charts/issues/434), since this is our use case, but from my perspective it’s fair to have it in *both* charts. Here, to support it during the installation of the `azuredisk-csi` which would allow Snapshotting with whatever tool one wants ot use and in the Velero chart for the usage of `velero` when the `csi-driver` does not come with the support for this.

**Describe the solution you'd like in detail**
I would like to have the possibility for:

```
createVolumeSnapshotClass: enabled # defaults to disabled
volumeSnapshotClasses:
  - name: csi-azuredisk-vsc
    driver: disk.csi.azure.com
    deletionPolicy: Delete
    parameters:
      - incremental: true
    additionalLabels:  
      - velero.io/csi-volumesnapshot-class: "true" should always be added 
      - label1: true
      - label2: test
```

**Describe alternatives you've considered**
It’s pretty use to just `kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml`, but also pretty hacky.

**Additional context**
Also here: I’m willing to implement this, but I would require a :+1: or to be confident, that this proposed feature request could be merged.

**Comment by andyzhangx** [comment]
hi @janaurka I think this requirement is reasonable, about the detailed implementation, not sure whether below format is supported in chart config:

```
volumeSnapshotClasses:
  - name: csi-azuredisk-vsc
    driver: disk.csi.azure.com
    deletionPolicy: Delete
    parameters:
      - incremental: true
    additionalLabels:  
      - velero.io/csi-volumesnapshot-class: "true" should always be added 
      - label1: true
      - label2: test
  ```
