### ISSUE TITLE
Could not detach PremiumV2_LRS volume

### ISSUE THREAD

**Issue by TBurda** [kubernetes-sigs/azuredisk-csi-driver#1715]
**What happened**:

Error blocking removal of persistent volume from cluster. 

`
GRPC error: rpc error: code = Internal desc = Could not detach volume xxxx from node aks-lin001-41409696-vmss000000: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400,
RawError: { "error": { "code": "InvalidParameter", "message": "Storage Account type PremiumV2_LRS is not supported with caching type ReadOnly. Please use caching type None.", "target": "dataDisk.caching" }}
`

Disk PremiumV2_LRS (Static Provisioning):
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-data-redis
status:
  phase: Released
spec:
  capacity:
    storage: 4Gi
  csi:
    driver: disk.csi.azure.com
    volumeHandle: xxxxx
    volumeAttributes:
      cachingMode: ReadOnly
      fsType: ext4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: managed-csi
  volumeMode: Filesystem
```

**Environment**:

- CSI Driver version: v1.24.0.2
- Kubernetes version (use `kubectl version`): AKS v1.24.9
- OS (e.g. from /etc/os-release): Ubuntu 18.04.6 LTS (linux (amd64))
- Kernel (e.g. `uname -a`): 5.4.0-1100-azure
