### ISSUE TITLE
Missing arm64 images for v1.27.1 helm chart 

### ISSUE THREAD

**Issue by jgreat** [kubernetes-sigs/azuredisk-csi-driver#1865]
**What happened**:

csi-azuredisk-controller pods go into ImagePullBackOff for the following images when installed with the v1.27.1 helm chart:

- mcr.microsoft.com/oss/kubernetes-csi/csi-attacher:v4.0.0
- mcr.microsoft.com/oss/kubernetes-csi/csi-provisioner:v3.3.0
- mcr.microsoft.com/oss/kubernetes-csi/csi-resizer:v1.6.0

**How to reproduce it**:

values.yaml
```
controller:
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"
  replicas: 1
feature:
  enableFSGroupPolicy: true
snapshot:
  enabled: true
```

Helm install
```
helm upgrade azuredisk-csi-driver azuredisk-csi -i -f ./values.yaml --version  v1.27.1
```
