### ISSUE TITLE
PremiumV2_LRS is not supported sku/storageaccounttype

### ISSUE THREAD

**Issue by davidkarlsen** [kubernetes-sigs/azuredisk-csi-driver#1952]
**What happened**:
```shell
  Warning  ProvisioningFailed    2s (x4 over 9s)    disk.csi.azure.com_ftm-aro-dev-nore-aro-m62hr-master-0_86358903-cf57-4bc5-8d36-e6f669a938c0  failed to provision volume with StorageClass "test": rpc error: code = InvalidArgument desc = azureDisk - PremiumV2_LRS is not supported sku/storageaccounttype. Supported values are [Premium_LRS Premium_ZRS Standard_LRS StandardSSD_LRS StandardSSD_ZRS UltraSSD_LRS]
```

**What you expected to happen**:
PV to be created

**How to reproduce it**:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test
parameters:
  kind: Managed
  storageaccounttype: PremiumV2_LRS
 provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

**Anything else we need to know?**:
az tells us it is supported region:
```shell
az
az vm list-skus --resource-type disks --query "[?name=='PremiumV2_LRS'].{Region:locationInfo[0].location, Zones:locationInfo[0].zones}" 

[
  {
    "Region": "norwayeast",
    "Zones": [
      "3"
    ]
  }
]

```

ARO v4.12

**Environment**:

- CSI Driver version: ARO bundled, v1.22.0
- Kubernetes version (use `kubectl version`): v1.25.11+1485cc9
- OS (e.g. from /etc/os-release): RHCOS
- Kernel (e.g. `uname -a`): 4.18.0-372.69.1.el8_6.x86_64
- Install tools:
- Others:
