### ISSUE TITLE
Cannot provision PV in ReadWriteMany mode. MULTI_NODE_MULTI_WRITER error.

### ISSUE THREAD

**Issue by DanyloMikula** [kubernetes-sigs/azuredisk-csi-driver#2122]
**What happened**:

I'm trying to deploy an application that needs to use storage in ReadWriteMany access mode.
PVC stuck in pending with the following error:

```
Events:
  Type     Reason                Age               From                                                                                               Message
  ----     ------                ----              ----                                                                                               -------
  Normal   Provisioning          7s (x5 over 22s)  disk.csi.azure.com_csi-azuredisk-controller-7d7977b9bf-bwrmd_fe3f4243-375f-45fd-ac04-28d2c2bb061f  External provisioner is provisioning volume for claim "web/wordpress"
  Warning  ProvisioningFailed    7s (x5 over 22s)  disk.csi.azure.com_csi-azuredisk-controller-7d7977b9bf-bwrmd_fe3f4243-375f-45fd-ac04-28d2c2bb061f  failed to provision volume with StorageClass "azuredisk-csi-standard-lrs": rpc error: code = InvalidArgument desc = mountVolume is not supported for access mode: MULTI_NODE_MULTI_WRITER
  Normal   ExternalProvisioning  0s (x3 over 22s)  persistentvolume-controller                                                                        Waiting for a volume to be created either by the external provisioner 'disk.csi.azure.com' or manually by the system administrator. If volume creation is delayed, please verify that the provisioner is running and correctly registered.
```

Here is my storage class config that I'm trying to use:

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azuredisk-csi-standard-lrs
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
  maxShares: "3"
  cachingMode: None
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

Helm chart storage config:

```
persistence:
  enabled: true
  accessModes:
    - ReadWriteMany
  storageClass: "azuredisk-csi-standard-lrs"
  size: 32Gi

```
Helm chart itself: https://github.com/bitnami/charts/tree/main/bitnami/wordpress

**What you expected to happen**:

A new disc should be provisioned and work in ReadWriteMany mode.

**Anything else we need to know?**:

The following features are enabled:
Microsoft.Compute/SsdZrsManagedDisks
Microsoft.ContainerService/EnableAzureDiskFileCSIDriver

**Environment**:

- CSI Driver version: v1.29.1
- Kubernetes version (use `kubectl version`): v1.28.3
- OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): Linux aks-default-21870540-vmss000000 5.15.0-1051-azure 59-Ubuntu SMP Wed Oct 11 18:49:16 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
