### ISSUE TITLE
Valid Tag Values are altered in created resources

### ISSUE THREAD

**Issue by mroger-mtb** [kubernetes-sigs/azuredisk-csi-driver#2245]
**What happened**:
Tag values are being altered inappropriately. Certain valid characters such as '/' are being replaced with '-' when the disk is created.
a tag declared as: 
`Environment=Dev/Test`
is created like so
`Environment=Dev-Test`

This prevents the resources from being created under tagging policies that have requirements on tag values

**What you expected to happen**:
the '/' character should not be replaced with '-'

**How to reproduce it**:
Create a storage class with a tags parameter:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: disk-tagged-managed
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: 'true'
provisioner: disk.csi.azure.com
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
  tags: Environment=Dev/Test,GL Code=74300-000-700/370,Product=Engage
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

then create a PVC is using this storage class,
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
    volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: disk-tagged-managed
  volumeMode: Filesystem
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
   image: mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.28.6
- Kubernetes version (use `kubectl version`):
  Client Version: v1.28.3
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.27.7
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
