### ISSUE TITLE
Provision a disk from snapshot

### ISSUE THREAD

**Issue by GabriFedi97** [kubernetes-sigs/azuredisk-csi-driver#2301]
**What happened**:

Restoring a disk from an existing snapshot seems to not be working properly with the `disk.csi.azure.com`, when the snapshot and the AKS resource groups are different. I have a disk snapshot `snapshot-xxxxxxxxxx` on resource group `resource_group_A` and an AKS cluster on resource group `resource_group_B`, belonging to the same subscription and tenant. I need to consume the snapshot on the AKS to create a new PersistentVolume and PersistentVolumeClaim and so, a new disk should be created, restored by the snapshot. To do that, I went through the following steps:

1. Create a `VolumeSnapshot` on AKS:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-xxxxxxxxxx
  namespace: default
spec:
  source:
    volumeSnapshotContentName: snapshot-xxxxxxxxxx
  volumeSnapshotClassName: csi-azuredisk-vsc
```

2. Created a `VolumeSnapshotContent`, setting the `source.snapshotHandle` with the id of the snapshot source:

```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: snapshot-xxxxxxxxxx
spec:
  deletionPolicy: Delete
  driver: disk.csi.azure.com
  source:
    snapshotHandle: /subscriptions/my_sub/resourceGroups/resource_group_A/providers/Microsoft.Compute/snapshots/snapshot-xxxxxxxxxx
  volumeSnapshotClassName: csi-azuredisk-vsc
  volumeSnapshotRef:
    apiVersion: snapshot.storage.k8s.io/v1
    kind: VolumeSnapshot
    name: snapshot-xxxxxxxxxx
    namespace: default
```

3. Created a PersistentVolumeClaim having the volume snapshot as data source:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
    volume.kubernetes.io/storage-provisioner: disk.csi.azure.com
  name: snapshot-xxxxxxxxxx
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  dataSource:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name:  snapshot-xxxxxxxxxx
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name:  snapshot-xxxxxxxxxx
  resources:
    requests:
      storage: 4Gi
  storageClassName: edb-azure-premium-v1-immediate
  volumeMode: Filesystem
```

**What you expected to happen**:

I expect the csi driver to create a new disk, restoring from the snapshot, to get attached to a new PersistenVolume in my AKS cluster on resource group `resource_group_B`. 
Checking the PVC events, it looks like that the driver doesn't get to find the snapshot resource:

```
Warning  ProvisioningFailed  75s (x8 over 3m26s)  disk.csi.azure.com_csi-azuredisk-controller-7956cd9559-rnz6q_bda34993-63bf-4ee2-9ec1-c01b10f9af30  failed to provision volume with StorageClass "edb-azure-premium-v1-immediate": rpc error: code = NotFound desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {\r
  "error": {\r
    "code": "NotFound",\r
    "message": "Resource snapshot-xxxxxxxxxx is not found."\r
  }\r
```

**How to reproduce it**:

Create a snapshot of a disk on a resource group and try to consume it through a `VolumeSnapshotContent` and `VolumeSnapshot` on a different resource group.

**Anything else we need to know?**:

This is not happening if the AKS and snapshot are in the same resource group. In this case, a new disk get provisioner properly and PV and PVC get created accordingly.
I cannot get further logs from the csi driver pods, since the driver has been deployed and managed by AKS. Attempting to update the `--v` argument from 5 to 1 for the `azuredisk` in the `csi-azuredisk-node` has no effect, as the change gets reverted after few seconds. 

**Environment**:

- CSI Driver version:  `v1.29.3`
- Kubernetes version (use `kubectl version`): `v1.28.3`
- OS (e.g. from /etc/os-release): `Ubuntu 22.04.4 LTS`
- Kernel (e.g. `uname -a`): `5.15.0-1060-azure` 
- Install tools:
- Others:
