### ISSUE TITLE
Duplicate imagePullSecrets in v2 chart templates

### ISSUE THREAD

**Issue by gitolicious** [kubernetes-sigs/azuredisk-csi-driver#2835]
**What happened**:
When rendering the chart templates, multiple resources end up with duplicate and malformed `imagePullSecrets` in their `spec`.

**What you expected to happen**:
Redering should result in well-formed k8s resources with single and correct `imagePullSecrets`

**How to reproduce it**:
* Set a pull secret in `charts/latest-v2/azuredisk-csi-driver/values.yaml` according to docs
  ```yaml
  imagePullSecrets:
  - name: "image-pull-secret"
  ```
* Render the template
  ```sh
  helm template azuredisk-csi-driver ./charts/latest-v2/azuredisk-csi-driver -f ./charts/latest-v2/azuredisk-csi-driver/values.yaml --show-only templates/csi-azuredisk-node.yaml
  ```
* Observe output
  ```yaml
  [...]
  kind: DaemonSet
  apiVersion: apps/v1
  metadata:
    name: csi-azuredisk-node
  [...]
  spec:
  [...]
    template:
  [...]
      spec:
        imagePullSecrets:
          - name: image-pull-secret
  [...]
        imagePullSecrets:
          - name: map[name:image-pull-secret]
  ```

As seen, the `imagePullSecrets` attribute exists twice. One is originating from the chart file directly

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/1425d7f7dd1b98b41f8f1f0bd5163f011eee35f5/charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml#L66-L69

and one is injected by the `_helpers.tpl`

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/1425d7f7dd1b98b41f8f1f0bd5163f011eee35f5/charts/latest-v2/azuredisk-csi-driver/templates/_helpers.tpl#L19-L26

added here:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/1425d7f7dd1b98b41f8f1f0bd5163f011eee35f5/charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml#L89

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: latest-v2
- Kubernetes version (use `kubectl version`): n/a
- OS (e.g. from /etc/os-release): n/a
- Kernel (e.g. `uname -a`): n/a
- Install tools: n/a
- Others: n/a
