### ISSUE TITLE
It is impossible to customize node affinity for controllers due to a bug in template

### ISSUE THREAD

**Issue by olegch** [kubernetes-sigs/azuredisk-csi-driver#2858]
**What happened**:

Affinity specified in `controller.affinity` property in the `values.yaml` is not included in the controllers' manifests.

**What you expected to happen**:

Both azuredisk cotroller and snapshot controller are generated with the required affinity.

**How to reproduce it**:

Run the chart
```
helm template azuredisk-csi-driver \
  --repo https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts azuredisk-csi-driver \
  --version 1.31.2 \
  -f values.yaml
```
with the following `values.yaml`:
```
controller:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: example.io/csi
            operator: Exists

snapshot:
  enabled: true
  VolumeSnapshotClass:
    enabled: true
```
Required affinity is not generated for any of the controllers.

**Anything else we need to know?**:

It seems to be due to a mistake in usage of `contains` helm template function at 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml#L42
and
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml#L45

Arguments order must be reversed or pipeline should be used,
moreover indentation in the following `toYaml` line has to be fixed as follows:
```
    {{- if tpl "{{ .Values.controller.affinity }}" . | contains "nodeSelectorTerms" }}
      {{- with .Values.controller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
    ...
```
Moreover, the use of this condition does not seem necessary, or is even actually harmful.
What if the user just wants to specify a purely pod affinity or anti-affinity rather than node affinity.

**Environment**:

- CSI Driver version: 1.31.2 and all others
- Kubernetes version (use `kubectl version`): 1.31.3
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): 6.8.0-52-generic #53-Ubuntu SMP PREEMPT_DYNAMIC Sat Jan 11 00:06:25 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: helm
- Others:
