### ISSUE TITLE
add a test case for WriteAccelerator feature

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#292]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like in detail**

PR(https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/291)
added a new parameter(`writeAcceleratorEnabled` case insensitive) in azure disk storage class, for static provisioning, user needs to add a new tag(`writeacceleratorenabled` case **sensitive**) on azure disk before using as disk PV.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
provisioner: kubernetes.io/azure-disk
parameters:
  skuname: Premium_LRS
  writeAcceleratorEnabled: true
```

`WriteAccelerator` require specific Azure VM size, we could add a negative e2e case first, so if `writeAcceleratorEnabled: true` is added on current unsupported e2e test vm size, attach disk should fail.

**Additional context**
