### ISSUE TITLE
`Resizing` condition not removed from PVC status while Waiting for pod restarting

### ISSUE THREAD

**Issue by mbiagetti** [kubernetes-sigs/azuredisk-csi-driver#3027]
**weird scenario during PVC resize**:

`Resizing` condition not removed from PVC status when transitioning to `FileSystemResizePending`

```yaml
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-08T15:53:24Z"
    status: "True"
    type: Resizing
  - lastProbeTime: null
    lastTransitionTime: "2025-04-08T15:53:27Z"
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
    status: "True"
    type: FileSystemResizePending
  phase: Bound

```

**What you expected to happen**:

On other cloud providers, the `Resizing` condition is removed when the transition to `FileSystemResizePending` , like:

```yaml
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 4Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-08T15:53:27Z"
    message: Waiting for user to (re-)start a pod to finish file system resize of
      volume on node.
    status: "True"
    type: FileSystemResizePending
  phase: Bound

```

**How to reproduce it**:

Resize request

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.31.5
- Kubernetes version (use `kubectl version`): v1.31
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others: node info:

```
  nodeInfo:
    architecture: amd64
    bootID: b57b136e-af34-40a2-a54d-b85f0706f470
    containerRuntimeVersion: containerd://1.7.27-1
    kernelVersion: 5.15.0-1084-azure
    kubeProxyVersion: v1.31.5
    kubeletVersion: v1.31.5
    machineID: 625e890245f04fe08182eac4ed54ccaa
    operatingSystem: linux
    osImage: Ubuntu 22.04.5 LTS
```
