### ISSUE TITLE
Corrupted file system with multiple managed-csi-premium (disk.csi.azure.com) volumes

### ISSUE THREAD

**Issue by MatteoBrentegani** [kubernetes-sigs/azuredisk-csi-driver#3029]
**What happened**:
When i create multiple Windows pods with a pvc managed-csi-premium the file system is corrupted. It should be empty but some pods have multiple file and folder which referes to something else.

![Image](https://github.com/user-attachments/assets/9fd0d477-fa52-4f72-9ff0-c12d179c7b33)

We don't know where these files are coming from but we are sure that the files are not related to our Docker image

The issue can be reproduce manually but we have the same problem within our CICD environment based on Jenkins

**What you expected to happen**:
The pod file system should be empty

**How to reproduce it**:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc-1
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-csi-premium
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc-2
spec:
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 8Gi
  storageClassName: managed-csi-premium
---
apiVersion: "v1"
kind: "Pod"

metadata:
  name: my-windows-pod-1
  namespace: default

spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/windows:10.0.17763.6293
      volumeMounts:
        - name: dynamic-volume
          mountPath: "C:\\\\jenkins"
      workingDir: "C:\\\\jenkins"
      command: [ "powershell.exe", "-Command" ]
      args: [ "while ($true) { Start-Sleep -Seconds 300 }" ]
  volumes:
    - name: dynamic-volume
      persistentVolumeClaim:
        claimName: dynamic-pvc-1
  nodeSelector:
    jenkins/agent: "windows"
  restartPolicy: "Never"
  tolerations:
  - effect: "NoSchedule"
    key: "jenkinspipeline"
    operator: "Equal"
    value: "true"
---
apiVersion: "v1"
kind: "Pod"

metadata:
  name: my-windows-pod-2
  namespace: default

spec:
  containers:
    - name: windows-container
      image: mcr.microsoft.com/windows:10.0.17763.6293
      volumeMounts:
        - name: dynamic-volume
          mountPath: "C:\\\\jenkins"
      workingDir: "C:\\\\jenkins"
      command: [ "powershell.exe", "-Command" ]
      args: [ "while ($true) { Start-Sleep -Seconds 300 }" ]
  volumes:
    - name: dynamic-volume
      persistentVolumeClaim:
        claimName: dynamic-pvc-2
  nodeSelector:
    jenkins/agent: "windows"
  restartPolicy: "Never"
  tolerations:
  - effect: "NoSchedule"
    key: "jenkinspipeline"
    operator: "Equal"
    value: "true"
```
Running `dir` inside of each pod to see the issue.
The problem occur starting from kubernetes 1.31. The previous versions are working propertly

**Anything else we need to know?**:

**Environment**:

- CSI Driver version: v1.31.6
- Kubernetes version (use `kubectl version`):
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.31.5
- OS (e.g. from /etc/os-release): the version of the nodes or my working station?
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
