### ISSUE TITLE
Support for tags parameter in VolumeSnapshotClass

### ISSUE THREAD

**Issue by celiawa** [kubernetes-sigs/azuredisk-csi-driver#358]
We have policy set to only allow the resources to be created with some specific tags.
We can create the pv with below tags added in storageclass. 
parameters:
  ...
  tags: 'TicketURL=*****'

But when create snapshot, it failed to pass the policy after we added the tags in the volumesnapshotclass.

Can we support to add tags in snapshot.

Azure csi version: v0.6.0
Kubernetes version: v1.17.4

**Comment by ZeroMagic** [comment]
@celiawa  Thanks for your report. I will add it as soon as possible.

**Comment by andyzhangx** [comment]
@celiawa It's already supported in master branch:
```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-azuredisk-vsc
driver: disk.csi.azure.com
deletionPolicy: Delete
parameters:
  tags: 'foo=aaa,bar=bbb'  # Tag names are case-insensitive and are limited to 512 characters. Tag values are case-sensitive and are limited to 256 characters.
```

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md#volumesnapshotclass
