### ISSUE TITLE
Volume Clone: failed to provision new volume if source volume and copied volume are in different zone

### ISSUE THREAD

**Issue by koceg** [kubernetes-sigs/azuredisk-csi-driver#571]
**What happened**:

Generated from disk.csi.azure.com_xxxxxxxxxx 6 times in the last minute
failed to provision volume with StorageClass "azuredisk-csi": rpc error: code = Unknown desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 400, RawError: { "error": { "code": "InvalidParameter", "message": "The resource 'pvc-80a6b8d2-c6a8-499c-abf1-cfac8e7398eb' in an availability zone cannot be copied from the source '/subscriptions/X-X-X-X-X/resourceGroups/xxxxxxxxxx/providers/Microsoft.Compute/disks/pvc-6f9d7a67-9249-42e7-8eec-ffa7c3eaf8ed' in a different availability zone.", "target": "sourceResourceId" } }

**What you expected to happen**:
new volume to be created/cloned from existing one 

**How to reproduce it**:
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk-csi
parameters:
  location: westeurope
  resourceGroup: xxxxxxxxx
  skuname: StandardSSD_LRS
  storageAccount: xxxxxxxxxx
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: azuredisk-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azuredisk-clone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk-csi
  resources:
    requests:
      storage: 10Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-azuredisk
```
**Anything else we need to know?**:

**Environment**: Openshift 4.5.13 on Azure
- CSI Driver version:  azuredisk-csi:v0.9.0
- Kubernetes version (use `kubectl version`):  v1.18.3+47c0e71
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
looks like you are copying from disk pvc from zone#1 to zone#2, and it's not supported

**Comment by koceg** [comment]
How can I specify that I want to clone the disk in the same zone as the first provision?

**Comment by andyzhangx** [comment]
if you set `volumeBindingMode: WaitForFirstConsumer` in storage class and make the 2nd pod(with pvc-azuredisk-clone) schedule on same node as 1st pod(with pvc-azuredisk), it should work.

**Comment by koceg** [comment]
After applying `volumeBindingMode: WaitForFirstConsumer` to storage class this ended up in a dead lock
- first pod starts successfully
- pvc-azuredisk-clone volume in pending state
- and after I create the second pod 
  `Unable to attach or mount volumes: unmounted volumes=[azuredisk01], unattached volumes=[default-token-qs249 azuredisk01]: error processing PVC namespace/pvc-azuredisk-clone: PVC is not bound`

and I get the original error as well

at this point I'd rather use snapshot volume and create my PVC from there. What is suggested here might work, but seems wrong to me.
```
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azuredisk
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: nginx
      name: nginx-azuredisk
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
      resources:
        limits:
          memory: "64Mi"
          cpu: "200m"
      volumeMounts:
        - name: azuredisk01
          mountPath: "/mnt/azuredisk"
  volumes:
    - name: azuredisk01
      persistentVolumeClaim:
        claimName: pvc-azuredisk
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azuredisk-clone
spec:
  nodeName: same-as-nginx-azuredisk-pod
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: nginx
      name: nginx-azuredisk
      args:
        - sleep
        - "3600"
      resources:
        limits:
          memory: "64Mi"
          cpu: "200m"
      volumeMounts:
        - name: azuredisk01
          mountPath: "/mnt/azuredisk"
  volumes:
    - name: azuredisk01
      persistentVolumeClaim:
        claimName: pvc-azuredisk-clone
```
