### ISSUE TITLE
getNodeVMSet assumes availability set or scale set

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes-sigs/azuredisk-csi-driver#576]
**What happened**:

https://kubernetes.slack.com/archives/CEX9HENG7/p1603926809189800?thread_ts=1602177910.055200&cid=CEX9HENG7

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go#L94 assumes availability set or scale set. When using VMs with availability zones (not in availability sets) it fails with: `AttachVolume.Attach failed for volume "pvc-84f57545-0f8c-4087-b9ab-a04f500e6218" : failed to get azure instance id for node "capz-target-cluster-md-0-xs8cn" (not a vmss instance)` (error returned by https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/pkg/azuredisk/controllerserver.go#L409).

In a cluster with both VMs and VMSS nodes, where cloud provider config VMType is vmss. Setting the cloud provider config to standard would work but this is not an acceptable solution for mixed type clusters (ref https://github.com/kubernetes-sigs/cloud-provider-azure/issues/338). Are availability sets required for standalone VMs? What about VMs in Availability Zones? 

**What you expected to happen**:  `getNodeVMSet` should have a 4th option for VMs not in availability sets.

**How to reproduce it**:

1. provision a capz cluster with the default flavor (in eastus)
3. kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/master/templates/addons/storageclass-azure-disk.yaml
4. kubectl apply -f pvc.yaml 

where pvc.yaml is:

```
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-example
  labels:
    app: nginx
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-logs
  namespace: nginx-example
  labels:
    app: nginx
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
        labels:
            app: nginx
    spec:
        volumes:
        - name: nginx-logs
          persistentVolumeClaim:
            claimName: nginx-logs
        containers:
        - image: nginx:1.17.6
          name: nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/var/log/nginx"
            name: nginx-logs
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-nginx
  namespace: nginx-example
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
```

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: 
- Kubernetes version (use `kubectl version`): 1.18.8
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
