### ISSUE TITLE
add external Kubernetes e2e tests in CI pipeline

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#577]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Kubernetes offers so called external tests, where it can run e2e tests against an installed CSI drivers.
See https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external

The step to run e2e test:
 - make WHAT=test/e2e/e2e.test in k8s repo
 - Install Azuredisk driver to the cluster
```
   ginkgo -focus=‘External.Storage.*works.after.modifying.source.data.*’ \
       -skip=‘\[Disruptive\]|\[Serial\]’ \
       “$E2E_BINARY_PATH” \
       -- \
       -storage.testdriver=“$DRIVER_CONFIG” (edited) 
```

The Driver config file can be something like this:
```yaml
StorageClass:
  FromExistingClassName: azure-csi
SnapshotClass:
  FromExistingClassName: azure-csi-snapshotclass
DriverInfo:
  Name: disk.csi.azure.com
  SupportedSizeRange:
    Min: 10Gi
  RequiredAccessModes:
  - ReadWriteOnce
  Capabilities:
    persistence: true
    multipods: true
    exec: true
    block: true
    fsGroup: true
    topology: true
    controllerExpansion: true
    nodeExpansion: false
    volumeLimits: true
    snapshotDataSource: false
  StressTestOptions:
    NumPods: 10
    NumRestarts: 20
    NumSnapshots: 10
```
This should be able to run the snapshot related tests.

You can change the ginkgo focus to run other testsuites

**Describe alternatives you've considered**

**Additional context**
