### ISSUE TITLE
[CSI migration] add inline volume e2e test

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#729]
**Is your feature request related to a problem?/Why is this needed**

**Describe the solution you'd like in detail**

Need to verify it works first and then add add inline volume e2e test

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuredisk
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  azureDisk:
    diskName: {disk-id}
    diskURI: /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
    kind: Managed
    cachingMode: ReadOnly
    fsType: ext4
    readOnly: false
```
https://github.com/andyzhangx/demo/tree/master/linux/azuredisk#static-provisioning-for-azure-disk

**Describe alternatives you've considered**

**Additional context**
