### ISSUE TITLE
check zone support

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#86]
**What happened**:
I don't think zone is supported on current driver now:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/81900f30e195ae60b3ddd805d4304a4429105868/pkg/azuredisk/controllerserver.go#L114-L125

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
support zone feature like following:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ultrassd
provisioner: blobfuse.csi.azure.com
parameters:
  skuname: UltraSSD_LRS
  kind: managed
  cachingMode: ReadOnly
  diskIopsReadWrite: "1400"
  diskMbpsReadWrite: "320"
  zone: "1"
```
