### ISSUE TITLE
provide skuName for static PV

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azuredisk-csi-driver#984]
**Is your feature request related to a problem?/Why is this needed**

In static PV, there is no `skuName`, azure backup team needs this field in backup & restore scenario.

```yaml
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    readOnly: false
    volumeHandle: /subscriptions/{sub-id}/resourcegroups/{group-name}/providers/microsoft.compute/disks/{disk-id}
    volumeAttributes:
      fsType: ext4
```

Here difficulty is how to pass `skuName` in `ControllerPublishVolume`?

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**
