### ISSUE TITLE
invalid parameter storageAccount

### ISSUE THREAD

**Issue by gmcbrien** [kubernetes-sigs/azuredisk-csi-driver#994]
**What happened**:
Updated azuredisk CSI driver in line with release 1.6.0. When provisioning a PVC, it sticks in 'Pending' with the following error:

```
Events:
  Type     Reason                Age                From                                                                                                                  Message
  ----     ------                ----               ----                                                                                                                  -------
  Normal   Provisioning          16s (x6 over 45s)  disk.csi.azure.com_m-e-1-cluster-xxxxx-2-pdrd9_2e0cf2fd-87ab-4a30-9a3d-6d79817de4dd  External provisioner is provisioning volume for claim "sandbox/pvc-azuredisk-test"
  Warning  ProvisioningFailed    16s (x6 over 45s)  disk.csi.azure.com_m-e-1-cluster-xxxxx-2-pdrd9_2e0cf2fd-87ab-4a30-9a3d-6d79817de4dd  failed to provision volume with StorageClass "azuredisk-csi": rpc error: code = Unknown desc = invalid parameter storageAccount in storage class
  Normal   ExternalProvisioning  8s (x4 over 45s)   persistentvolume-controller                                                                                           waiting for a volume to be created, either by external provisioner "disk.csi.azure.com" or manually created by system administrator
```

As far as I can see [here ](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/driver-parameters.md)storageAccount is a valid parameter.

This worked fine with my previous version (v0.10.0)

Here is my current storageclass config:

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azuredisk-csi
parameters:
  location: westeurope
  resourceGroup: m-e-1-cluster-xxxxx-rg
  skuname: StandardSSD_LRS
  storageAccount: clusterXXXXX
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**What you expected to happen**:
Create a PVC

**How to reproduce it**:

Deploy version 1.6.0 and try to create a PVC

**Anything else we need to know?**:
As we use ArgoCD, Ihave adapted our code to match the 1.6.0 release (image versions, syntax etc)

**Environment**:
- CSI Driver version: `1.6.0`
- Kubernetes version (use `kubectl version`):
```
Client Version: 4.7.13
Server Version: 4.7.18
Kubernetes Version: v1.20.0+87cc9a4
```
